Download etcd binaries from custom URL
githubixx/ansible-role-etcd pull request #29
Opened 2022-12-19 17:44 UTC by DanOPT

Changes:
- Added task to download tarball from custom URL
- Added variable `etcd_custom_download` to defaults
- Added required information to use this option in README.md

Fixes #28

2022-12-26 13:01 UTC, githubixx requested changes

2022-12-27 12:29 UTC, DanOPT commented on defaults/main.yml
> +etcd_custom_download: false
You're right. I wasn't sure about this, too.

2022-12-27 12:29 UTC, DanOPT commented
@githubixx I applied your changes and added the variable names to the task to make the values accessible.

2022-12-27 17:23 UTC, githubixx approved these changes

2022-12-27 17:24 UTC, merged